repos:
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
  -   id: pylint
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.780
  hooks:
  - id: mypy
    args: [--strict, --pretty]
    additional_dependencies: ["sqlalchemy", "sqlalchemy2-stubs"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-merge-conflict
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
  - id: forbid-crlf
  - id: forbid-tabs
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ['@commitlint/config-conventional']
